steps:
  build-node:
    image: coralhl/woodpecker-buildx-plugin
    settings:
      platforms: linux/amd64
      repo: coralhl/nginx-php8-fpm-node
      registry: docker.io
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      dockerfile: Dockerfile.node
      tags:
      - latest
      - php8.2.16
  build-php:
    image: coralhl/woodpecker-buildx-plugin
    settings:
      platforms: linux/amd64
      repo: coralhl/nginx-php8-fpm
      registry: docker.io
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      dockerfile: Dockerfile
      tags:
      - latest
      - php8.2.16

