FROM node:20.11-alpine3.19 AS nodejs

FROM ghcr.io/coralhl/nginx-php8-fpm:php8.2.16

LABEL org.opencontainers.image.authors="coral (coralhl@gmail.com)"
LABEL org.opencontainers.image.url="https://www.github.com/coralhl/nginx-php8-fpm"
LABEL org.opencontainers.image.source="https://www.github.com/coralhl/nginx-php8-fpm"

USER root

WORKDIR /var/www/html

COPY --from=nodejs /opt /opt
COPY --from=nodejs /usr/local /usr/local

RUN npm install -g svgo

EXPOSE 443 80

CMD ["/start.sh"]
