#!/bin/bash
# Create our noisy chown alias to handle read-only/remote volumes
# https://github.com/linuxserver/docker-mods/blob/mod-scripts/docker-mods.v3

chown "$@" || printf '**** Permissions could not be set. This is probably because your volume mounts are remote or read-only. ****\n**** The app may not work properly and we will not provide support for it. ****\n'
